version: 0.0
os: linux
files:
  - source: app
    destination: /var/www
  - source: scripts/webapi.service
    destination: /etc/systemd/system
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 120
      runas: root